"""Terrain-aware hybrid-gait planning interfaces.

This package owns planning data expressed in the world frame.  Geometry,
kinematics, gait execution, and motor control remain separate layers.
"""

from .types import (
    ContactCandidate,
    ContactState,
    GaitConstraints,
    HybridPlanningRequest,
    HybridTrajectory,
    InitialRobotState,
    MotionMode,
    RectangularObstacle,
    RimId,
    SwingTarget,
    TerrainProfile,
    TraversalGoal,
)
from .trajectory_io import write_trajectory_csv
from .terrain_2d import (
    RectangleObstacle as RectangleObstacle2D,
    SurfaceOrientation,
    TerrainProfile as TerrainProfile2D,
    TerrainSurface2D,
    TerrainSurfaceKind,
    plot_terrain_profile_2d,
    terrain_surface_rows,
)
from .geometry_2d import (
    HipPose2D,
    SampledLegGeometry2D,
    legacy_rim_edge_margin_rad,
    plot_leg_geometry_with_terrain_2d,
    sampled_leg_geometry_from_legacy_records,
    transform_points_hip_to_world,
    transform_points_world_to_hip,
)
from .terrain_query_2d import (
    PointTerrainQueryResult2D,
    SurfaceGapResult2D,
    plot_point_terrain_query_2d,
    point_terrain_gap_rows,
    query_point_to_terrain_surfaces_2d,
)
from .contact_detection_2d import (
    ContactCandidate2D,
    ContactDetectionResult2D,
    ContactQueryResult2D,
    VerticalFaceCollision2D,
    VerticalFaceCollisionResult2D,
    contact_candidate_rows,
    detect_contact_candidates_2d,
    detect_rectangle_vertical_face_collisions_2d,
    plot_contact_candidates_2d,
    plot_contact_query_2d,
    query_contact,
    vertical_face_collision_rows,
)

__all__ = [
    "ContactCandidate",
    "ContactCandidate2D",
    "ContactDetectionResult2D",
    "ContactQueryResult2D",
    "VerticalFaceCollision2D",
    "VerticalFaceCollisionResult2D",
    "ContactState",
    "GaitConstraints",
    "HybridPlanningRequest",
    "HybridTrajectory",
    "HipPose2D",
    "legacy_rim_edge_margin_rad",
    "InitialRobotState",
    "MotionMode",
    "PointTerrainQueryResult2D",
    "RectangularObstacle",
    "RectangleObstacle2D",
    "RimId",
    "SampledLegGeometry2D",
    "SwingTarget",
    "TerrainProfile",
    "TerrainProfile2D",
    "TerrainSurface2D",
    "TerrainSurfaceKind",
    "SurfaceOrientation",
    "SurfaceGapResult2D",
    "TraversalGoal",
    "write_trajectory_csv",
    "plot_terrain_profile_2d",
    "plot_leg_geometry_with_terrain_2d",
    "plot_point_terrain_query_2d",
    "plot_contact_candidates_2d",
    "plot_contact_query_2d",
    "query_contact",
    "contact_candidate_rows",
    "detect_contact_candidates_2d",
    "detect_rectangle_vertical_face_collisions_2d",
    "point_terrain_gap_rows",
    "query_point_to_terrain_surfaces_2d",
    "sampled_leg_geometry_from_legacy_records",
    "terrain_surface_rows",
    "transform_points_hip_to_world",
    "transform_points_world_to_hip",
    "vertical_face_collision_rows",
]
