"""Offline terrain-aware Walk planning for one known rectangular obstacle.

Steps 1--3 hold the state, assembly and touchdown contracts.  Steps 4--6 add
the arbitrary-touchdown swing, the world-fixed mixed-height stance and the
event scheduler.  Step 7 (``traversal`` and ``export``) composes those into a
single continuous trajectory and writes the hardware CSV set.
"""

from legwheel.planners.obstacle_walk.flat_adapter import (
    flat_walk_segment_from_generator,
    generate_flat_walk_segment,
)
from legwheel.planners.obstacle_walk.assembly import (
    BoundaryContinuityReport,
    ConcatenationResult,
    ContinuityTolerances,
    SegmentContinuityError,
    concatenate_segments,
    slice_segment,
    validate_segment_boundary,
)
from legwheel.planners.obstacle_walk.types import (
    LEG_ORDER,
    JOINT_ORDER,
    CommandOrder,
    LegId,
    SegmentType,
    TrajectorySegment,
    WalkState,
)
from legwheel.planners.obstacle_walk.terrain import (
    RectangleObstacle1D,
    TouchdownQueryResult,
    TouchdownRejectReason,
    TouchdownStatus,
    WalkTerrain1D,
    query_touchdown_surface,
)
from legwheel.planners.obstacle_walk.swing import (
    FullGeometryCollisionChecker,
    SwingPlanResult,
    SwingPlanningError,
    SwingRejectReason,
    generate_swing_segment,
    plot_swing_plan,
)
from legwheel.planners.obstacle_walk.stance import (
    BODY_TRAJECTORY_ASSUMPTION,
    StancePlanResult,
    StancePlanningError,
    StanceRejectReason,
    generate_stance_segment,
    plot_stance_plan,
)
from legwheel.planners.obstacle_walk.handoff import (
    FlatHandoffError,
    cycle_sample_count,
    flat_approach_segment,
    handover_contact_height_error_m,
    launch_sample_index,
)
from legwheel.planners.obstacle_walk.traversal import (
    BODY_POSE_POLICY,
    STANCE_CONTACT_MODEL,
    ObstacleTraversalError,
    ObstacleWalkRequest,
    ObstacleWalkResult,
    SegmentRecord,
    TraversalRejectReason,
    TraversalStage,
    build_walk_generator,
    generate_obstacle_walk,
    touchdown_candidates,
    walk_swing_order,
    wheel_face_exclusion_m,
)
from legwheel.planners.obstacle_walk.collision import (
    DEFAULT_ARC_SAMPLES,
    LegGeometrySampler,
    RectangleGeometryCollisionChecker,
    build_collision_checker,
    build_terrain_profile_2d,
)
from legwheel.planners.obstacle_walk.validation import (
    CheckResult,
    CheckStatus,
    TraversalValidationReport,
    validate_traversal,
)
from legwheel.planners.obstacle_walk.export import (
    CONTROLLER_DT_S,
    CONTROLLER_TRANSFORM_DURATION_S,
    CONTROLLER_TRANSFORM_ROWS,
    HARDWARE_COLUMN_NAMES,
    PHASE_COLUMN_NAMES,
    ExportPaths,
    build_prep_rows,
    resample_for_csv_controller,
    to_hardware_order,
    write_obstacle_walk_csv,
)
from legwheel.planners.obstacle_walk.scheduler import (
    FlatSegmentRequest,
    ObstacleScheduleError,
    ObstacleWalkSchedule,
    ScheduleRejectReason,
    ScheduleRequestKind,
    SegmentRequest,
    SwingSegmentRequest,
    schedule_obstacle_walk,
    schedule_to_dict,
)

__all__ = [
    "LEG_ORDER",
    "FlatHandoffError",
    "cycle_sample_count",
    "flat_approach_segment",
    "handover_contact_height_error_m",
    "launch_sample_index",
    "DEFAULT_ARC_SAMPLES",
    "CheckResult",
    "CheckStatus",
    "LegGeometrySampler",
    "RectangleGeometryCollisionChecker",
    "TraversalValidationReport",
    "build_collision_checker",
    "build_terrain_profile_2d",
    "validate_traversal",
    "BODY_POSE_POLICY",
    "STANCE_CONTACT_MODEL",
    "HARDWARE_COLUMN_NAMES",
    "PHASE_COLUMN_NAMES",
    "CONTROLLER_DT_S",
    "CONTROLLER_TRANSFORM_DURATION_S",
    "CONTROLLER_TRANSFORM_ROWS",
    "ExportPaths",
    "ObstacleTraversalError",
    "ObstacleWalkRequest",
    "ObstacleWalkResult",
    "SegmentRecord",
    "TraversalRejectReason",
    "TraversalStage",
    "build_prep_rows",
    "resample_for_csv_controller",
    "build_walk_generator",
    "generate_obstacle_walk",
    "to_hardware_order",
    "touchdown_candidates",
    "walk_swing_order",
    "wheel_face_exclusion_m",
    "write_obstacle_walk_csv",
    "JOINT_ORDER",
    "CommandOrder",
    "BoundaryContinuityReport",
    "BODY_TRAJECTORY_ASSUMPTION",
    "ConcatenationResult",
    "ContinuityTolerances",
    "FullGeometryCollisionChecker",
    "FlatSegmentRequest",
    "LegId",
    "ObstacleScheduleError",
    "ObstacleWalkSchedule",
    "SegmentType",
    "TrajectorySegment",
    "TouchdownQueryResult",
    "TouchdownRejectReason",
    "TouchdownStatus",
    "WalkState",
    "WalkTerrain1D",
    "RectangleObstacle1D",
    "SegmentContinuityError",
    "SegmentRequest",
    "ScheduleRejectReason",
    "ScheduleRequestKind",
    "StancePlanResult",
    "StancePlanningError",
    "StanceRejectReason",
    "SwingPlanResult",
    "SwingPlanningError",
    "SwingRejectReason",
    "SwingSegmentRequest",
    "concatenate_segments",
    "flat_walk_segment_from_generator",
    "generate_flat_walk_segment",
    "generate_swing_segment",
    "generate_stance_segment",
    "plot_stance_plan",
    "plot_swing_plan",
    "schedule_obstacle_walk",
    "schedule_to_dict",
    "slice_segment",
    "query_touchdown_surface",
    "validate_segment_boundary",
]
