"""Regression tests for asymmetric lateral stance lead fraction."""

import importlib.util
import inspect
from pathlib import Path

import numpy as np
import pytest

from legwheel.planners.gait_generator_3d import GaitGenerator3D
from legwheel.planners.launch_controller import LaunchController
from legwheel.planners.trajectory_planning_3d import TrajectoryPlanner3D

GENERATE_SCRIPT = (
    Path(__file__).resolve().parents[1] / "examples" / "gait" / "generate_hardware_csv.py"
)


def _load_generate_module():
    spec = importlib.util.spec_from_file_location("generate_hardware_csv", GENERATE_SCRIPT)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_lead_fraction_must_be_in_closed_unit_interval():
    """Lead fraction κ is a fraction of lateral travel assigned before mid-stance."""
    for value in (-0.01, 1.01):
        with pytest.raises(ValueError, match="lead_fraction"):
            TrajectoryPlanner3D(lead_fraction=value)


def test_kappa_zero_starts_lateral_stance_without_touchdown_lead():
    """κ=0 starts at zero lateral lead and accumulates travel toward liftoff."""
    planner = TrajectoryPlanner3D(
        stand_height=0.25,
        velocity=[0.10, 0.04, 0.0],
        period=1.0,
        dt=0.01,
        stance_duty=0.6,
        lead_fraction=0.0,
    )

    commands = planner.generate_trajectory()

    assert planner.gamma_touchdown == pytest.approx(0.0)
    assert commands[0][2] == pytest.approx(0.0)
    assert planner.gamma_liftoff < 0.0


def test_gait_generator_forwards_lead_fraction_to_every_leg():
    """The four leg planners must use the same κ selected for the body gait."""
    gait = GaitGenerator3D(
        stand_height=0.25,
        twist=[0.0, 0.10, 0.04],
        period=1.0,
        gait_type="Trot",
        dt=0.01,
        lead_fraction=0.0,
    )

    assert gait.lead_fraction == 0.0
    assert all(planner.lead_fraction == 0.0 for planner in gait.planners)


def test_default_kappa_half_is_byte_identical_to_legacy_generator():
    """Default κ=0.5 must preserve the trajectory generated by commit 64ffb406."""
    default = GaitGenerator3D(
        stand_height=0.25,
        twist=[0.0, 0.10, 0.04],
        step_height=0.05,
        period=1.0,
        gait_type="Trot",
        dt=0.01,
    ).generate_full_gait(1)
    explicit = GaitGenerator3D(
        stand_height=0.25,
        twist=[0.0, 0.10, 0.04],
        step_height=0.05,
        period=1.0,
        gait_type="Trot",
        dt=0.01,
        lead_fraction=0.5,
    ).generate_full_gait(1)

    assert np.array_equal(default, explicit)


def test_launch_controller_accepts_lead_fraction():
    """Launch ramp cycles must retain the selected lateral lead fraction."""
    launch = LaunchController(
        gait_type="Trot",
        stand_height=0.25,
        twist=[0.0, 0.10, 0.04],
        lead_fraction=0.0,
    )

    assert launch.lead_fraction == 0.0


def test_hardware_csv_generator_accepts_lead_fraction():
    """The experiment CSV entry point must expose κ explicitly."""
    module = _load_generate_module()
    signature = inspect.signature(module.generate_hardware_csv)

    assert signature.parameters["lead_fraction"].default == 0.5


def test_workspace_guard_accounts_for_asymmetric_lateral_excursion():
    """κ=0 has half the safe lateral travel of the symmetric κ=0.5 stance."""
    symmetric = GaitGenerator3D(
        stand_height=0.25,
        twist=[0.0, 0.0, 0.60],
        period=1.0,
        gait_type="Trot",
        dt=0.01,
        lead_fraction=0.5,
    )
    one_sided = GaitGenerator3D(
        stand_height=0.25,
        twist=[0.0, 0.0, 0.60],
        period=1.0,
        gait_type="Trot",
        dt=0.01,
        lead_fraction=0.0,
    )

    assert one_sided.v_com[1] == pytest.approx(symmetric.v_com[1] / 2.0)
